/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using asana.Client;
using asana.Api;
using asana.Model;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing AttachmentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AttachmentsApiTests
    {
        private AttachmentsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AttachmentsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AttachmentsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' AttachmentsApi
            //Assert.IsInstanceOf(typeof(AttachmentsApi), instance);
        }

        
        /// <summary>
        /// Test CreateAttachmentForObject
        /// </summary>
        [Test]
        public void CreateAttachmentForObjectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? optPretty = null;
            //List<string> optFields = null;
            //string resourceSubtype = null;
            //System.IO.Stream file = null;
            //string parent = null;
            //string url = null;
            //string name = null;
            //var response = instance.CreateAttachmentForObject(optPretty, optFields, resourceSubtype, file, parent, url, name);
            //Assert.IsInstanceOf(typeof(GetAttachment200Response), response, "response is GetAttachment200Response");
        }
        
        /// <summary>
        /// Test DeleteAttachment
        /// </summary>
        [Test]
        public void DeleteAttachmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string attachmentGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.DeleteAttachment(attachmentGid, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(DeleteAttachment200Response), response, "response is DeleteAttachment200Response");
        }
        
        /// <summary>
        /// Test GetAttachment
        /// </summary>
        [Test]
        public void GetAttachmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string attachmentGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.GetAttachment(attachmentGid, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(GetAttachment200Response), response, "response is GetAttachment200Response");
        }
        
        /// <summary>
        /// Test GetAttachmentsForObject
        /// </summary>
        [Test]
        public void GetAttachmentsForObjectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string parent = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //int? limit = null;
            //string offset = null;
            //var response = instance.GetAttachmentsForObject(parent, optPretty, optFields, limit, offset);
            //Assert.IsInstanceOf(typeof(GetAttachmentsForObject200Response), response, "response is GetAttachmentsForObject200Response");
        }
        
    }

}
