/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using asana.Client;
using asana.Api;
using asana.Model;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing OrganizationExportsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OrganizationExportsApiTests
    {
        private OrganizationExportsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrganizationExportsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrganizationExportsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' OrganizationExportsApi
            //Assert.IsInstanceOf(typeof(OrganizationExportsApi), instance);
        }

        
        /// <summary>
        /// Test CreateOrganizationExport
        /// </summary>
        [Test]
        public void CreateOrganizationExportTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateOrganizationExportRequest createOrganizationExportRequest = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //int? limit = null;
            //string offset = null;
            //var response = instance.CreateOrganizationExport(createOrganizationExportRequest, optPretty, optFields, limit, offset);
            //Assert.IsInstanceOf(typeof(CreateOrganizationExport201Response), response, "response is CreateOrganizationExport201Response");
        }
        
        /// <summary>
        /// Test GetOrganizationExport
        /// </summary>
        [Test]
        public void GetOrganizationExportTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string organizationExportGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.GetOrganizationExport(organizationExportGid, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(CreateOrganizationExport201Response), response, "response is CreateOrganizationExport201Response");
        }
        
    }

}
