/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using asana.Client;
using asana.Api;
using asana.Model;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing ProjectStatusesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProjectStatusesApiTests
    {
        private ProjectStatusesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProjectStatusesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProjectStatusesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' ProjectStatusesApi
            //Assert.IsInstanceOf(typeof(ProjectStatusesApi), instance);
        }

        
        /// <summary>
        /// Test CreateProjectStatusForProject
        /// </summary>
        [Test]
        public void CreateProjectStatusForProjectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectGid = null;
            //CreateProjectStatusForProjectRequest createProjectStatusForProjectRequest = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.CreateProjectStatusForProject(projectGid, createProjectStatusForProjectRequest, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(GetProjectStatus200Response), response, "response is GetProjectStatus200Response");
        }
        
        /// <summary>
        /// Test DeleteProjectStatus
        /// </summary>
        [Test]
        public void DeleteProjectStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectStatusGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.DeleteProjectStatus(projectStatusGid, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(DeleteAttachment200Response), response, "response is DeleteAttachment200Response");
        }
        
        /// <summary>
        /// Test GetProjectStatus
        /// </summary>
        [Test]
        public void GetProjectStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectStatusGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.GetProjectStatus(projectStatusGid, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(GetProjectStatus200Response), response, "response is GetProjectStatus200Response");
        }
        
        /// <summary>
        /// Test GetProjectStatusesForProject
        /// </summary>
        [Test]
        public void GetProjectStatusesForProjectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //int? limit = null;
            //string offset = null;
            //var response = instance.GetProjectStatusesForProject(projectGid, optPretty, optFields, limit, offset);
            //Assert.IsInstanceOf(typeof(GetProjectStatusesForProject200Response), response, "response is GetProjectStatusesForProject200Response");
        }
        
    }

}
