/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using asana.Client;
using asana.Api;
using asana.Model;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing StoriesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class StoriesApiTests
    {
        private StoriesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StoriesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoriesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' StoriesApi
            //Assert.IsInstanceOf(typeof(StoriesApi), instance);
        }

        
        /// <summary>
        /// Test CreateStoryForTask
        /// </summary>
        [Test]
        public void CreateStoryForTaskTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskGid = null;
            //UpdateStoryRequest updateStoryRequest = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.CreateStoryForTask(taskGid, updateStoryRequest, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(GetStory200Response), response, "response is GetStory200Response");
        }
        
        /// <summary>
        /// Test DeleteStory
        /// </summary>
        [Test]
        public void DeleteStoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string storyGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.DeleteStory(storyGid, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(DeleteAttachment200Response), response, "response is DeleteAttachment200Response");
        }
        
        /// <summary>
        /// Test GetStoriesForTask
        /// </summary>
        [Test]
        public void GetStoriesForTaskTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //int? limit = null;
            //string offset = null;
            //var response = instance.GetStoriesForTask(taskGid, optPretty, optFields, limit, offset);
            //Assert.IsInstanceOf(typeof(GetStoriesForTask200Response), response, "response is GetStoriesForTask200Response");
        }
        
        /// <summary>
        /// Test GetStory
        /// </summary>
        [Test]
        public void GetStoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string storyGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //int? limit = null;
            //string offset = null;
            //var response = instance.GetStory(storyGid, optPretty, optFields, limit, offset);
            //Assert.IsInstanceOf(typeof(GetStory200Response), response, "response is GetStory200Response");
        }
        
        /// <summary>
        /// Test UpdateStory
        /// </summary>
        [Test]
        public void UpdateStoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string storyGid = null;
            //UpdateStoryRequest updateStoryRequest = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.UpdateStory(storyGid, updateStoryRequest, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(GetStory200Response), response, "response is GetStory200Response");
        }
        
    }

}
