/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using asana.Client;
using asana.Api;
using asana.Model;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing TeamMembershipsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TeamMembershipsApiTests
    {
        private TeamMembershipsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TeamMembershipsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TeamMembershipsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' TeamMembershipsApi
            //Assert.IsInstanceOf(typeof(TeamMembershipsApi), instance);
        }

        
        /// <summary>
        /// Test GetTeamMembership
        /// </summary>
        [Test]
        public void GetTeamMembershipTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string teamMembershipGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.GetTeamMembership(teamMembershipGid, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(GetTeamMembership200Response), response, "response is GetTeamMembership200Response");
        }
        
        /// <summary>
        /// Test GetTeamMemberships
        /// </summary>
        [Test]
        public void GetTeamMembershipsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? optPretty = null;
            //List<string> optFields = null;
            //int? limit = null;
            //string offset = null;
            //string team = null;
            //string user = null;
            //string workspace = null;
            //var response = instance.GetTeamMemberships(optPretty, optFields, limit, offset, team, user, workspace);
            //Assert.IsInstanceOf(typeof(GetTeamMemberships200Response), response, "response is GetTeamMemberships200Response");
        }
        
        /// <summary>
        /// Test GetTeamMembershipsForTeam
        /// </summary>
        [Test]
        public void GetTeamMembershipsForTeamTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string teamGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //int? limit = null;
            //string offset = null;
            //var response = instance.GetTeamMembershipsForTeam(teamGid, optPretty, optFields, limit, offset);
            //Assert.IsInstanceOf(typeof(GetTeamMemberships200Response), response, "response is GetTeamMemberships200Response");
        }
        
        /// <summary>
        /// Test GetTeamMembershipsForUser
        /// </summary>
        [Test]
        public void GetTeamMembershipsForUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userGid = null;
            //string workspace = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //int? limit = null;
            //string offset = null;
            //var response = instance.GetTeamMembershipsForUser(userGid, workspace, optPretty, optFields, limit, offset);
            //Assert.IsInstanceOf(typeof(GetTeamMemberships200Response), response, "response is GetTeamMemberships200Response");
        }
        
    }

}
