/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using asana.Client;
using asana.Api;
using asana.Model;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing TypeaheadApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TypeaheadApiTests
    {
        private TypeaheadApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TypeaheadApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TypeaheadApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' TypeaheadApi
            //Assert.IsInstanceOf(typeof(TypeaheadApi), instance);
        }

        
        /// <summary>
        /// Test TypeaheadForWorkspace
        /// </summary>
        [Test]
        public void TypeaheadForWorkspaceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string workspaceGid = null;
            //string resourceType = null;
            //string type = null;
            //string query = null;
            //int? count = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.TypeaheadForWorkspace(workspaceGid, resourceType, type, query, count, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(TypeaheadForWorkspace200Response), response, "response is TypeaheadForWorkspace200Response");
        }
        
    }

}
