/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using asana.Client;
using asana.Api;
using asana.Model;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing UsersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UsersApiTests
    {
        private UsersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UsersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UsersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' UsersApi
            //Assert.IsInstanceOf(typeof(UsersApi), instance);
        }

        
        /// <summary>
        /// Test GetFavoritesForUser
        /// </summary>
        [Test]
        public void GetFavoritesForUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userGid = null;
            //string resourceType = null;
            //string workspace = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.GetFavoritesForUser(userGid, resourceType, workspace, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(GetFavoritesForUser200Response), response, "response is GetFavoritesForUser200Response");
        }
        
        /// <summary>
        /// Test GetUser
        /// </summary>
        [Test]
        public void GetUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.GetUser(userGid, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(GetUser200Response), response, "response is GetUser200Response");
        }
        
        /// <summary>
        /// Test GetUsers
        /// </summary>
        [Test]
        public void GetUsersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string workspace = null;
            //string team = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //int? limit = null;
            //string offset = null;
            //var response = instance.GetUsers(workspace, team, optPretty, optFields, limit, offset);
            //Assert.IsInstanceOf(typeof(GetUsers200Response), response, "response is GetUsers200Response");
        }
        
        /// <summary>
        /// Test GetUsersForTeam
        /// </summary>
        [Test]
        public void GetUsersForTeamTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string teamGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //string offset = null;
            //var response = instance.GetUsersForTeam(teamGid, optPretty, optFields, offset);
            //Assert.IsInstanceOf(typeof(GetUsers200Response), response, "response is GetUsers200Response");
        }
        
        /// <summary>
        /// Test GetUsersForWorkspace
        /// </summary>
        [Test]
        public void GetUsersForWorkspaceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string workspaceGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //string offset = null;
            //var response = instance.GetUsersForWorkspace(workspaceGid, optPretty, optFields, offset);
            //Assert.IsInstanceOf(typeof(GetUsers200Response), response, "response is GetUsers200Response");
        }
        
    }

}
