/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using asana.Client;
using asana.Api;
using asana.Model;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing WebhooksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class WebhooksApiTests
    {
        private WebhooksApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WebhooksApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhooksApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' WebhooksApi
            //Assert.IsInstanceOf(typeof(WebhooksApi), instance);
        }

        
        /// <summary>
        /// Test CreateWebhook
        /// </summary>
        [Test]
        public void CreateWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateWebhookRequest createWebhookRequest = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.CreateWebhook(createWebhookRequest, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(CreateWebhook201Response), response, "response is CreateWebhook201Response");
        }
        
        /// <summary>
        /// Test DeleteWebhook
        /// </summary>
        [Test]
        public void DeleteWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string webhookGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.DeleteWebhook(webhookGid, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(DeleteAttachment200Response), response, "response is DeleteAttachment200Response");
        }
        
        /// <summary>
        /// Test GetWebhook
        /// </summary>
        [Test]
        public void GetWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string webhookGid = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.GetWebhook(webhookGid, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(CreateWebhook201Response), response, "response is CreateWebhook201Response");
        }
        
        /// <summary>
        /// Test GetWebhooks
        /// </summary>
        [Test]
        public void GetWebhooksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string workspace = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //int? limit = null;
            //string offset = null;
            //string resource = null;
            //var response = instance.GetWebhooks(workspace, optPretty, optFields, limit, offset, resource);
            //Assert.IsInstanceOf(typeof(GetWebhooks200Response), response, "response is GetWebhooks200Response");
        }
        
        /// <summary>
        /// Test UpdateWebhook
        /// </summary>
        [Test]
        public void UpdateWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string webhookGid = null;
            //UpdateWebhookRequest updateWebhookRequest = null;
            //bool? optPretty = null;
            //List<string> optFields = null;
            //var response = instance.UpdateWebhook(webhookGid, updateWebhookRequest, optPretty, optFields);
            //Assert.IsInstanceOf(typeof(CreateWebhook201Response), response, "response is CreateWebhook201Response");
        }
        
    }

}
