/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = asana.Client.OpenAPIDateConverter;

namespace asana.Model
{
    /// <summary>
    /// GoalRequestAllOf
    /// </summary>
    [DataContract]
    public partial class GoalRequestAllOf :  IEquatable<GoalRequestAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GoalRequestAllOf" /> class.
        /// </summary>
        /// <param name="team">*Conditional*. This property is only present when the &#x60;workspace&#x60; provided is an organization..</param>
        /// <param name="workspace">The &#x60;gid&#x60; of a workspace..</param>
        /// <param name="followers">followers.</param>
        /// <param name="timePeriod">The &#x60;gid&#x60; of a time period..</param>
        /// <param name="owner">The &#x60;gid&#x60; of a user..</param>
        public GoalRequestAllOf(string team = default(string), string workspace = default(string), List<string> followers = default(List<string>), string timePeriod = default(string), string owner = default(string))
        {
            this.Team = team;
            this.TimePeriod = timePeriod;
            this.Owner = owner;
            this.Team = team;
            this.Workspace = workspace;
            this.Followers = followers;
            this.TimePeriod = timePeriod;
            this.Owner = owner;
        }

        /// <summary>
        /// *Conditional*. This property is only present when the &#x60;workspace&#x60; provided is an organization.
        /// </summary>
        /// <value>*Conditional*. This property is only present when the &#x60;workspace&#x60; provided is an organization.</value>
        [DataMember(Name="team", EmitDefaultValue=true)]
        public string Team { get; set; }

        /// <summary>
        /// The &#x60;gid&#x60; of a workspace.
        /// </summary>
        /// <value>The &#x60;gid&#x60; of a workspace.</value>
        [DataMember(Name="workspace", EmitDefaultValue=false)]
        public string Workspace { get; set; }

        /// <summary>
        /// Gets or Sets Followers
        /// </summary>
        [DataMember(Name="followers", EmitDefaultValue=false)]
        public List<string> Followers { get; set; }

        /// <summary>
        /// The &#x60;gid&#x60; of a time period.
        /// </summary>
        /// <value>The &#x60;gid&#x60; of a time period.</value>
        [DataMember(Name="time_period", EmitDefaultValue=true)]
        public string TimePeriod { get; set; }

        /// <summary>
        /// The &#x60;gid&#x60; of a user.
        /// </summary>
        /// <value>The &#x60;gid&#x60; of a user.</value>
        [DataMember(Name="owner", EmitDefaultValue=true)]
        public string Owner { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GoalRequestAllOf {\n");
            sb.Append("  Team: ").Append(Team).Append("\n");
            sb.Append("  Workspace: ").Append(Workspace).Append("\n");
            sb.Append("  Followers: ").Append(Followers).Append("\n");
            sb.Append("  TimePeriod: ").Append(TimePeriod).Append("\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GoalRequestAllOf);
        }

        /// <summary>
        /// Returns true if GoalRequestAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of GoalRequestAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GoalRequestAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Team == input.Team ||
                    (this.Team != null &&
                    this.Team.Equals(input.Team))
                ) && 
                (
                    this.Workspace == input.Workspace ||
                    (this.Workspace != null &&
                    this.Workspace.Equals(input.Workspace))
                ) && 
                (
                    this.Followers == input.Followers ||
                    this.Followers != null &&
                    input.Followers != null &&
                    this.Followers.SequenceEqual(input.Followers)
                ) && 
                (
                    this.TimePeriod == input.TimePeriod ||
                    (this.TimePeriod != null &&
                    this.TimePeriod.Equals(input.TimePeriod))
                ) && 
                (
                    this.Owner == input.Owner ||
                    (this.Owner != null &&
                    this.Owner.Equals(input.Owner))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Team != null)
                    hashCode = hashCode * 59 + this.Team.GetHashCode();
                if (this.Workspace != null)
                    hashCode = hashCode * 59 + this.Workspace.GetHashCode();
                if (this.Followers != null)
                    hashCode = hashCode * 59 + this.Followers.GetHashCode();
                if (this.TimePeriod != null)
                    hashCode = hashCode * 59 + this.TimePeriod.GetHashCode();
                if (this.Owner != null)
                    hashCode = hashCode * 59 + this.Owner.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
