/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = asana.Client.OpenAPIDateConverter;

namespace asana.Model
{
    /// <summary>
    /// PortfolioRemoveItemRequest
    /// </summary>
    [DataContract]
    public partial class PortfolioRemoveItemRequest :  IEquatable<PortfolioRemoveItemRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PortfolioRemoveItemRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PortfolioRemoveItemRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PortfolioRemoveItemRequest" /> class.
        /// </summary>
        /// <param name="item">The item to remove from the portfolio. (required).</param>
        public PortfolioRemoveItemRequest(string item = default(string))
        {
            // to ensure "item" is required (not null)
            if (item == null)
            {
                throw new InvalidDataException("item is a required property for PortfolioRemoveItemRequest and cannot be null");
            }
            else
            {
                this.Item = item;
            }

        }

        /// <summary>
        /// The item to remove from the portfolio.
        /// </summary>
        /// <value>The item to remove from the portfolio.</value>
        [DataMember(Name="item", EmitDefaultValue=true)]
        public string Item { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PortfolioRemoveItemRequest {\n");
            sb.Append("  Item: ").Append(Item).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PortfolioRemoveItemRequest);
        }

        /// <summary>
        /// Returns true if PortfolioRemoveItemRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of PortfolioRemoveItemRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PortfolioRemoveItemRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Item == input.Item ||
                    (this.Item != null &&
                    this.Item.Equals(input.Item))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Item != null)
                    hashCode = hashCode * 59 + this.Item.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
