/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = asana.Client.OpenAPIDateConverter;

namespace asana.Model
{
    /// <summary>
    /// ProjectStatusBaseAllOf
    /// </summary>
    [DataContract]
    public partial class ProjectStatusBaseAllOf :  IEquatable<ProjectStatusBaseAllOf>, IValidatableObject
    {
        /// <summary>
        /// The color associated with the status update.
        /// </summary>
        /// <value>The color associated with the status update.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ColorEnum
        {
            /// <summary>
            /// Enum Green for value: green
            /// </summary>
            [EnumMember(Value = "green")]
            Green = 1,

            /// <summary>
            /// Enum Yellow for value: yellow
            /// </summary>
            [EnumMember(Value = "yellow")]
            Yellow = 2,

            /// <summary>
            /// Enum Red for value: red
            /// </summary>
            [EnumMember(Value = "red")]
            Red = 3,

            /// <summary>
            /// Enum Blue for value: blue
            /// </summary>
            [EnumMember(Value = "blue")]
            Blue = 4

        }

        /// <summary>
        /// The color associated with the status update.
        /// </summary>
        /// <value>The color associated with the status update.</value>
        [DataMember(Name="color", EmitDefaultValue=true)]
        public ColorEnum Color { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectStatusBaseAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProjectStatusBaseAllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectStatusBaseAllOf" /> class.
        /// </summary>
        /// <param name="text">The text content of the status update. (required).</param>
        /// <param name="htmlText">[Opt In](/docs/input-output-options). The text content of the status update with formatting as HTML..</param>
        /// <param name="color">The color associated with the status update. (required).</param>
        public ProjectStatusBaseAllOf(string text = default(string), string htmlText = default(string), ColorEnum color = default(ColorEnum))
        {
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new InvalidDataException("text is a required property for ProjectStatusBaseAllOf and cannot be null");
            }
            else
            {
                this.Text = text;
            }

            // to ensure "color" is required (not null)
            if (color == null)
            {
                throw new InvalidDataException("color is a required property for ProjectStatusBaseAllOf and cannot be null");
            }
            else
            {
                this.Color = color;
            }

            this.HtmlText = htmlText;
        }

        /// <summary>
        /// The text content of the status update.
        /// </summary>
        /// <value>The text content of the status update.</value>
        [DataMember(Name="text", EmitDefaultValue=true)]
        public string Text { get; set; }

        /// <summary>
        /// [Opt In](/docs/input-output-options). The text content of the status update with formatting as HTML.
        /// </summary>
        /// <value>[Opt In](/docs/input-output-options). The text content of the status update with formatting as HTML.</value>
        [DataMember(Name="html_text", EmitDefaultValue=false)]
        public string HtmlText { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProjectStatusBaseAllOf {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  HtmlText: ").Append(HtmlText).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProjectStatusBaseAllOf);
        }

        /// <summary>
        /// Returns true if ProjectStatusBaseAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of ProjectStatusBaseAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProjectStatusBaseAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && 
                (
                    this.HtmlText == input.HtmlText ||
                    (this.HtmlText != null &&
                    this.HtmlText.Equals(input.HtmlText))
                ) && 
                (
                    this.Color == input.Color ||
                    (this.Color != null &&
                    this.Color.Equals(input.Color))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                if (this.HtmlText != null)
                    hashCode = hashCode * 59 + this.HtmlText.GetHashCode();
                if (this.Color != null)
                    hashCode = hashCode * 59 + this.Color.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
