/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = asana.Client.OpenAPIDateConverter;

namespace asana.Model
{
    /// <summary>
    /// WorkspaceResponseAllOf
    /// </summary>
    [DataContract]
    public partial class WorkspaceResponseAllOf :  IEquatable<WorkspaceResponseAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceResponseAllOf" /> class.
        /// </summary>
        /// <param name="emailDomains">The email domains that are associated with this workspace..</param>
        /// <param name="isOrganization">Whether the workspace is an *organization*..</param>
        public WorkspaceResponseAllOf(List<string> emailDomains = default(List<string>), bool isOrganization = default(bool))
        {
            this.EmailDomains = emailDomains;
            this.IsOrganization = isOrganization;
        }

        /// <summary>
        /// The email domains that are associated with this workspace.
        /// </summary>
        /// <value>The email domains that are associated with this workspace.</value>
        [DataMember(Name="email_domains", EmitDefaultValue=false)]
        public List<string> EmailDomains { get; set; }

        /// <summary>
        /// Whether the workspace is an *organization*.
        /// </summary>
        /// <value>Whether the workspace is an *organization*.</value>
        [DataMember(Name="is_organization", EmitDefaultValue=false)]
        public bool IsOrganization { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WorkspaceResponseAllOf {\n");
            sb.Append("  EmailDomains: ").Append(EmailDomains).Append("\n");
            sb.Append("  IsOrganization: ").Append(IsOrganization).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WorkspaceResponseAllOf);
        }

        /// <summary>
        /// Returns true if WorkspaceResponseAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of WorkspaceResponseAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkspaceResponseAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EmailDomains == input.EmailDomains ||
                    this.EmailDomains != null &&
                    input.EmailDomains != null &&
                    this.EmailDomains.SequenceEqual(input.EmailDomains)
                ) && 
                (
                    this.IsOrganization == input.IsOrganization ||
                    (this.IsOrganization != null &&
                    this.IsOrganization.Equals(input.IsOrganization))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EmailDomains != null)
                    hashCode = hashCode * 59 + this.EmailDomains.GetHashCode();
                if (this.IsOrganization != null)
                    hashCode = hashCode * 59 + this.IsOrganization.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
