/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing AttachmentResponseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttachmentResponseAllOfTests
    {
        // TODO uncomment below to declare an instance variable for AttachmentResponseAllOf
        //private AttachmentResponseAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AttachmentResponseAllOf
            //instance = new AttachmentResponseAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AttachmentResponseAllOf
        /// </summary>
        [Test]
        public void AttachmentResponseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AttachmentResponseAllOf
            //Assert.IsInstanceOf(typeof(AttachmentResponseAllOf), instance);
        }


        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'DownloadUrl'
        /// </summary>
        [Test]
        public void DownloadUrlTest()
        {
            // TODO unit test for the property 'DownloadUrl'
        }
        /// <summary>
        /// Test the property 'PermanentUrl'
        /// </summary>
        [Test]
        public void PermanentUrlTest()
        {
            // TODO unit test for the property 'PermanentUrl'
        }
        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Test]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }
        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Test]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'ViewUrl'
        /// </summary>
        [Test]
        public void ViewUrlTest()
        {
            // TODO unit test for the property 'ViewUrl'
        }

    }

}
