/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing AuditLogEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuditLogEventTests
    {
        // TODO uncomment below to declare an instance variable for AuditLogEvent
        //private AuditLogEvent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AuditLogEvent
            //instance = new AuditLogEvent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AuditLogEvent
        /// </summary>
        [Test]
        public void AuditLogEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AuditLogEvent
            //Assert.IsInstanceOf(typeof(AuditLogEvent), instance);
        }


        /// <summary>
        /// Test the property 'Gid'
        /// </summary>
        [Test]
        public void GidTest()
        {
            // TODO unit test for the property 'Gid'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Test]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }
        /// <summary>
        /// Test the property 'EventCategory'
        /// </summary>
        [Test]
        public void EventCategoryTest()
        {
            // TODO unit test for the property 'EventCategory'
        }
        /// <summary>
        /// Test the property 'Actor'
        /// </summary>
        [Test]
        public void ActorTest()
        {
            // TODO unit test for the property 'Actor'
        }
        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Test]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Test]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

    }

}
