/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing CustomFieldBaseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomFieldBaseAllOfTests
    {
        // TODO uncomment below to declare an instance variable for CustomFieldBaseAllOf
        //private CustomFieldBaseAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomFieldBaseAllOf
            //instance = new CustomFieldBaseAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomFieldBaseAllOf
        /// </summary>
        [Test]
        public void CustomFieldBaseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CustomFieldBaseAllOf
            //Assert.IsInstanceOf(typeof(CustomFieldBaseAllOf), instance);
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'EnumOptions'
        /// </summary>
        [Test]
        public void EnumOptionsTest()
        {
            // TODO unit test for the property 'EnumOptions'
        }
        /// <summary>
        /// Test the property 'Precision'
        /// </summary>
        [Test]
        public void PrecisionTest()
        {
            // TODO unit test for the property 'Precision'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'CustomLabel'
        /// </summary>
        [Test]
        public void CustomLabelTest()
        {
            // TODO unit test for the property 'CustomLabel'
        }
        /// <summary>
        /// Test the property 'CustomLabelPosition'
        /// </summary>
        [Test]
        public void CustomLabelPositionTest()
        {
            // TODO unit test for the property 'CustomLabelPosition'
        }
        /// <summary>
        /// Test the property 'IsGlobalToWorkspace'
        /// </summary>
        [Test]
        public void IsGlobalToWorkspaceTest()
        {
            // TODO unit test for the property 'IsGlobalToWorkspace'
        }
        /// <summary>
        /// Test the property 'HasNotificationsEnabled'
        /// </summary>
        [Test]
        public void HasNotificationsEnabledTest()
        {
            // TODO unit test for the property 'HasNotificationsEnabled'
        }

    }

}
