/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing CustomFieldCompactAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomFieldCompactAllOfTests
    {
        // TODO uncomment below to declare an instance variable for CustomFieldCompactAllOf
        //private CustomFieldCompactAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomFieldCompactAllOf
            //instance = new CustomFieldCompactAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomFieldCompactAllOf
        /// </summary>
        [Test]
        public void CustomFieldCompactAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CustomFieldCompactAllOf
            //Assert.IsInstanceOf(typeof(CustomFieldCompactAllOf), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ResourceSubtype'
        /// </summary>
        [Test]
        public void ResourceSubtypeTest()
        {
            // TODO unit test for the property 'ResourceSubtype'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'EnumOptions'
        /// </summary>
        [Test]
        public void EnumOptionsTest()
        {
            // TODO unit test for the property 'EnumOptions'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'DateValue'
        /// </summary>
        [Test]
        public void DateValueTest()
        {
            // TODO unit test for the property 'DateValue'
        }
        /// <summary>
        /// Test the property 'EnumValue'
        /// </summary>
        [Test]
        public void EnumValueTest()
        {
            // TODO unit test for the property 'EnumValue'
        }
        /// <summary>
        /// Test the property 'MultiEnumValues'
        /// </summary>
        [Test]
        public void MultiEnumValuesTest()
        {
            // TODO unit test for the property 'MultiEnumValues'
        }
        /// <summary>
        /// Test the property 'NumberValue'
        /// </summary>
        [Test]
        public void NumberValueTest()
        {
            // TODO unit test for the property 'NumberValue'
        }
        /// <summary>
        /// Test the property 'TextValue'
        /// </summary>
        [Test]
        public void TextValueTest()
        {
            // TODO unit test for the property 'TextValue'
        }
        /// <summary>
        /// Test the property 'DisplayValue'
        /// </summary>
        [Test]
        public void DisplayValueTest()
        {
            // TODO unit test for the property 'DisplayValue'
        }

    }

}
