/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing GetProjectMembershipsForProject200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetProjectMembershipsForProject200ResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetProjectMembershipsForProject200Response
        //private GetProjectMembershipsForProject200Response instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetProjectMembershipsForProject200Response
            //instance = new GetProjectMembershipsForProject200Response();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetProjectMembershipsForProject200Response
        /// </summary>
        [Test]
        public void GetProjectMembershipsForProject200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetProjectMembershipsForProject200Response
            //Assert.IsInstanceOf(typeof(GetProjectMembershipsForProject200Response), instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
