/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing GoalResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GoalResponseTests
    {
        // TODO uncomment below to declare an instance variable for GoalResponse
        //private GoalResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GoalResponse
            //instance = new GoalResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GoalResponse
        /// </summary>
        [Test]
        public void GoalResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GoalResponse
            //Assert.IsInstanceOf(typeof(GoalResponse), instance);
        }


        /// <summary>
        /// Test the property 'Gid'
        /// </summary>
        [Test]
        public void GidTest()
        {
            // TODO unit test for the property 'Gid'
        }
        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Test]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'HtmlNotes'
        /// </summary>
        [Test]
        public void HtmlNotesTest()
        {
            // TODO unit test for the property 'HtmlNotes'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'DueOn'
        /// </summary>
        [Test]
        public void DueOnTest()
        {
            // TODO unit test for the property 'DueOn'
        }
        /// <summary>
        /// Test the property 'StartOn'
        /// </summary>
        [Test]
        public void StartOnTest()
        {
            // TODO unit test for the property 'StartOn'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'IsWorkspaceLevel'
        /// </summary>
        [Test]
        public void IsWorkspaceLevelTest()
        {
            // TODO unit test for the property 'IsWorkspaceLevel'
        }
        /// <summary>
        /// Test the property 'Liked'
        /// </summary>
        [Test]
        public void LikedTest()
        {
            // TODO unit test for the property 'Liked'
        }
        /// <summary>
        /// Test the property 'Likes'
        /// </summary>
        [Test]
        public void LikesTest()
        {
            // TODO unit test for the property 'Likes'
        }
        /// <summary>
        /// Test the property 'NumLikes'
        /// </summary>
        [Test]
        public void NumLikesTest()
        {
            // TODO unit test for the property 'NumLikes'
        }
        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Test]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }
        /// <summary>
        /// Test the property 'Workspace'
        /// </summary>
        [Test]
        public void WorkspaceTest()
        {
            // TODO unit test for the property 'Workspace'
        }
        /// <summary>
        /// Test the property 'Followers'
        /// </summary>
        [Test]
        public void FollowersTest()
        {
            // TODO unit test for the property 'Followers'
        }
        /// <summary>
        /// Test the property 'TimePeriod'
        /// </summary>
        [Test]
        public void TimePeriodTest()
        {
            // TODO unit test for the property 'TimePeriod'
        }
        /// <summary>
        /// Test the property 'Metric'
        /// </summary>
        [Test]
        public void MetricTest()
        {
            // TODO unit test for the property 'Metric'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'CurrentStatusUpdate'
        /// </summary>
        [Test]
        public void CurrentStatusUpdateTest()
        {
            // TODO unit test for the property 'CurrentStatusUpdate'
        }

    }

}
