/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing PortfolioResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PortfolioResponseTests
    {
        // TODO uncomment below to declare an instance variable for PortfolioResponse
        //private PortfolioResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PortfolioResponse
            //instance = new PortfolioResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PortfolioResponse
        /// </summary>
        [Test]
        public void PortfolioResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PortfolioResponse
            //Assert.IsInstanceOf(typeof(PortfolioResponse), instance);
        }


        /// <summary>
        /// Test the property 'Gid'
        /// </summary>
        [Test]
        public void GidTest()
        {
            // TODO unit test for the property 'Gid'
        }
        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Test]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'CustomFieldSettings'
        /// </summary>
        [Test]
        public void CustomFieldSettingsTest()
        {
            // TODO unit test for the property 'CustomFieldSettings'
        }
        /// <summary>
        /// Test the property 'CurrentStatusUpdate'
        /// </summary>
        [Test]
        public void CurrentStatusUpdateTest()
        {
            // TODO unit test for the property 'CurrentStatusUpdate'
        }
        /// <summary>
        /// Test the property 'DueOn'
        /// </summary>
        [Test]
        public void DueOnTest()
        {
            // TODO unit test for the property 'DueOn'
        }
        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Test]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
        /// <summary>
        /// Test the property 'Members'
        /// </summary>
        [Test]
        public void MembersTest()
        {
            // TODO unit test for the property 'Members'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'StartOn'
        /// </summary>
        [Test]
        public void StartOnTest()
        {
            // TODO unit test for the property 'StartOn'
        }
        /// <summary>
        /// Test the property 'Workspace'
        /// </summary>
        [Test]
        public void WorkspaceTest()
        {
            // TODO unit test for the property 'Workspace'
        }
        /// <summary>
        /// Test the property 'PermalinkUrl'
        /// </summary>
        [Test]
        public void PermalinkUrlTest()
        {
            // TODO unit test for the property 'PermalinkUrl'
        }
        /// <summary>
        /// Test the property 'Public'
        /// </summary>
        [Test]
        public void PublicTest()
        {
            // TODO unit test for the property 'Public'
        }

    }

}
