/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing ProjectDuplicateRequestScheduleDates
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectDuplicateRequestScheduleDatesTests
    {
        // TODO uncomment below to declare an instance variable for ProjectDuplicateRequestScheduleDates
        //private ProjectDuplicateRequestScheduleDates instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProjectDuplicateRequestScheduleDates
            //instance = new ProjectDuplicateRequestScheduleDates();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProjectDuplicateRequestScheduleDates
        /// </summary>
        [Test]
        public void ProjectDuplicateRequestScheduleDatesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ProjectDuplicateRequestScheduleDates
            //Assert.IsInstanceOf(typeof(ProjectDuplicateRequestScheduleDates), instance);
        }


        /// <summary>
        /// Test the property 'ShouldSkipWeekends'
        /// </summary>
        [Test]
        public void ShouldSkipWeekendsTest()
        {
            // TODO unit test for the property 'ShouldSkipWeekends'
        }
        /// <summary>
        /// Test the property 'DueOn'
        /// </summary>
        [Test]
        public void DueOnTest()
        {
            // TODO unit test for the property 'DueOn'
        }
        /// <summary>
        /// Test the property 'StartOn'
        /// </summary>
        [Test]
        public void StartOnTest()
        {
            // TODO unit test for the property 'StartOn'
        }

    }

}
