/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing ProjectResponseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectResponseAllOfTests
    {
        // TODO uncomment below to declare an instance variable for ProjectResponseAllOf
        //private ProjectResponseAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProjectResponseAllOf
            //instance = new ProjectResponseAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProjectResponseAllOf
        /// </summary>
        [Test]
        public void ProjectResponseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ProjectResponseAllOf
            //Assert.IsInstanceOf(typeof(ProjectResponseAllOf), instance);
        }


        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Test]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
        /// <summary>
        /// Test the property 'Completed'
        /// </summary>
        [Test]
        public void CompletedTest()
        {
            // TODO unit test for the property 'Completed'
        }
        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Test]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }
        /// <summary>
        /// Test the property 'CompletedBy'
        /// </summary>
        [Test]
        public void CompletedByTest()
        {
            // TODO unit test for the property 'CompletedBy'
        }
        /// <summary>
        /// Test the property 'Followers'
        /// </summary>
        [Test]
        public void FollowersTest()
        {
            // TODO unit test for the property 'Followers'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Test]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }
        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Test]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }
        /// <summary>
        /// Test the property 'PermalinkUrl'
        /// </summary>
        [Test]
        public void PermalinkUrlTest()
        {
            // TODO unit test for the property 'PermalinkUrl'
        }
        /// <summary>
        /// Test the property 'ProjectBrief'
        /// </summary>
        [Test]
        public void ProjectBriefTest()
        {
            // TODO unit test for the property 'ProjectBrief'
        }
        /// <summary>
        /// Test the property 'CreatedFromTemplate'
        /// </summary>
        [Test]
        public void CreatedFromTemplateTest()
        {
            // TODO unit test for the property 'CreatedFromTemplate'
        }

    }

}
