/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing SectionTaskInsertRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SectionTaskInsertRequestTests
    {
        // TODO uncomment below to declare an instance variable for SectionTaskInsertRequest
        //private SectionTaskInsertRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SectionTaskInsertRequest
            //instance = new SectionTaskInsertRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SectionTaskInsertRequest
        /// </summary>
        [Test]
        public void SectionTaskInsertRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SectionTaskInsertRequest
            //Assert.IsInstanceOf(typeof(SectionTaskInsertRequest), instance);
        }


        /// <summary>
        /// Test the property 'Task'
        /// </summary>
        [Test]
        public void TaskTest()
        {
            // TODO unit test for the property 'Task'
        }
        /// <summary>
        /// Test the property 'InsertBefore'
        /// </summary>
        [Test]
        public void InsertBeforeTest()
        {
            // TODO unit test for the property 'InsertBefore'
        }
        /// <summary>
        /// Test the property 'InsertAfter'
        /// </summary>
        [Test]
        public void InsertAfterTest()
        {
            // TODO unit test for the property 'InsertAfter'
        }

    }

}
