/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing StatusUpdateResponseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatusUpdateResponseAllOfTests
    {
        // TODO uncomment below to declare an instance variable for StatusUpdateResponseAllOf
        //private StatusUpdateResponseAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StatusUpdateResponseAllOf
            //instance = new StatusUpdateResponseAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StatusUpdateResponseAllOf
        /// </summary>
        [Test]
        public void StatusUpdateResponseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StatusUpdateResponseAllOf
            //Assert.IsInstanceOf(typeof(StatusUpdateResponseAllOf), instance);
        }


        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Test]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'Hearted'
        /// </summary>
        [Test]
        public void HeartedTest()
        {
            // TODO unit test for the property 'Hearted'
        }
        /// <summary>
        /// Test the property 'Hearts'
        /// </summary>
        [Test]
        public void HeartsTest()
        {
            // TODO unit test for the property 'Hearts'
        }
        /// <summary>
        /// Test the property 'Liked'
        /// </summary>
        [Test]
        public void LikedTest()
        {
            // TODO unit test for the property 'Liked'
        }
        /// <summary>
        /// Test the property 'Likes'
        /// </summary>
        [Test]
        public void LikesTest()
        {
            // TODO unit test for the property 'Likes'
        }
        /// <summary>
        /// Test the property 'ModifiedAt'
        /// </summary>
        [Test]
        public void ModifiedAtTest()
        {
            // TODO unit test for the property 'ModifiedAt'
        }
        /// <summary>
        /// Test the property 'NumHearts'
        /// </summary>
        [Test]
        public void NumHeartsTest()
        {
            // TODO unit test for the property 'NumHearts'
        }
        /// <summary>
        /// Test the property 'NumLikes'
        /// </summary>
        [Test]
        public void NumLikesTest()
        {
            // TODO unit test for the property 'NumLikes'
        }
        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Test]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }

    }

}
