/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing StoryResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StoryResponseTests
    {
        // TODO uncomment below to declare an instance variable for StoryResponse
        //private StoryResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoryResponse
            //instance = new StoryResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoryResponse
        /// </summary>
        [Test]
        public void StoryResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StoryResponse
            //Assert.IsInstanceOf(typeof(StoryResponse), instance);
        }


        /// <summary>
        /// Test the property 'Gid'
        /// </summary>
        [Test]
        public void GidTest()
        {
            // TODO unit test for the property 'Gid'
        }
        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Test]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'ResourceSubtype'
        /// </summary>
        [Test]
        public void ResourceSubtypeTest()
        {
            // TODO unit test for the property 'ResourceSubtype'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'HtmlText'
        /// </summary>
        [Test]
        public void HtmlTextTest()
        {
            // TODO unit test for the property 'HtmlText'
        }
        /// <summary>
        /// Test the property 'IsPinned'
        /// </summary>
        [Test]
        public void IsPinnedTest()
        {
            // TODO unit test for the property 'IsPinned'
        }
        /// <summary>
        /// Test the property 'StickerName'
        /// </summary>
        [Test]
        public void StickerNameTest()
        {
            // TODO unit test for the property 'StickerName'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'IsEditable'
        /// </summary>
        [Test]
        public void IsEditableTest()
        {
            // TODO unit test for the property 'IsEditable'
        }
        /// <summary>
        /// Test the property 'IsEdited'
        /// </summary>
        [Test]
        public void IsEditedTest()
        {
            // TODO unit test for the property 'IsEdited'
        }
        /// <summary>
        /// Test the property 'Hearted'
        /// </summary>
        [Test]
        public void HeartedTest()
        {
            // TODO unit test for the property 'Hearted'
        }
        /// <summary>
        /// Test the property 'Hearts'
        /// </summary>
        [Test]
        public void HeartsTest()
        {
            // TODO unit test for the property 'Hearts'
        }
        /// <summary>
        /// Test the property 'NumHearts'
        /// </summary>
        [Test]
        public void NumHeartsTest()
        {
            // TODO unit test for the property 'NumHearts'
        }
        /// <summary>
        /// Test the property 'Liked'
        /// </summary>
        [Test]
        public void LikedTest()
        {
            // TODO unit test for the property 'Liked'
        }
        /// <summary>
        /// Test the property 'Likes'
        /// </summary>
        [Test]
        public void LikesTest()
        {
            // TODO unit test for the property 'Likes'
        }
        /// <summary>
        /// Test the property 'NumLikes'
        /// </summary>
        [Test]
        public void NumLikesTest()
        {
            // TODO unit test for the property 'NumLikes'
        }
        /// <summary>
        /// Test the property 'Previews'
        /// </summary>
        [Test]
        public void PreviewsTest()
        {
            // TODO unit test for the property 'Previews'
        }
        /// <summary>
        /// Test the property 'OldName'
        /// </summary>
        [Test]
        public void OldNameTest()
        {
            // TODO unit test for the property 'OldName'
        }
        /// <summary>
        /// Test the property 'NewName'
        /// </summary>
        [Test]
        public void NewNameTest()
        {
            // TODO unit test for the property 'NewName'
        }
        /// <summary>
        /// Test the property 'OldDates'
        /// </summary>
        [Test]
        public void OldDatesTest()
        {
            // TODO unit test for the property 'OldDates'
        }
        /// <summary>
        /// Test the property 'NewDates'
        /// </summary>
        [Test]
        public void NewDatesTest()
        {
            // TODO unit test for the property 'NewDates'
        }
        /// <summary>
        /// Test the property 'OldResourceSubtype'
        /// </summary>
        [Test]
        public void OldResourceSubtypeTest()
        {
            // TODO unit test for the property 'OldResourceSubtype'
        }
        /// <summary>
        /// Test the property 'NewResourceSubtype'
        /// </summary>
        [Test]
        public void NewResourceSubtypeTest()
        {
            // TODO unit test for the property 'NewResourceSubtype'
        }
        /// <summary>
        /// Test the property 'Story'
        /// </summary>
        [Test]
        public void StoryTest()
        {
            // TODO unit test for the property 'Story'
        }
        /// <summary>
        /// Test the property 'Assignee'
        /// </summary>
        [Test]
        public void AssigneeTest()
        {
            // TODO unit test for the property 'Assignee'
        }
        /// <summary>
        /// Test the property 'Follower'
        /// </summary>
        [Test]
        public void FollowerTest()
        {
            // TODO unit test for the property 'Follower'
        }
        /// <summary>
        /// Test the property 'OldSection'
        /// </summary>
        [Test]
        public void OldSectionTest()
        {
            // TODO unit test for the property 'OldSection'
        }
        /// <summary>
        /// Test the property 'NewSection'
        /// </summary>
        [Test]
        public void NewSectionTest()
        {
            // TODO unit test for the property 'NewSection'
        }
        /// <summary>
        /// Test the property 'Task'
        /// </summary>
        [Test]
        public void TaskTest()
        {
            // TODO unit test for the property 'Task'
        }
        /// <summary>
        /// Test the property 'Project'
        /// </summary>
        [Test]
        public void ProjectTest()
        {
            // TODO unit test for the property 'Project'
        }
        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Test]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'CustomField'
        /// </summary>
        [Test]
        public void CustomFieldTest()
        {
            // TODO unit test for the property 'CustomField'
        }
        /// <summary>
        /// Test the property 'OldTextValue'
        /// </summary>
        [Test]
        public void OldTextValueTest()
        {
            // TODO unit test for the property 'OldTextValue'
        }
        /// <summary>
        /// Test the property 'NewTextValue'
        /// </summary>
        [Test]
        public void NewTextValueTest()
        {
            // TODO unit test for the property 'NewTextValue'
        }
        /// <summary>
        /// Test the property 'OldNumberValue'
        /// </summary>
        [Test]
        public void OldNumberValueTest()
        {
            // TODO unit test for the property 'OldNumberValue'
        }
        /// <summary>
        /// Test the property 'NewNumberValue'
        /// </summary>
        [Test]
        public void NewNumberValueTest()
        {
            // TODO unit test for the property 'NewNumberValue'
        }
        /// <summary>
        /// Test the property 'OldEnumValue'
        /// </summary>
        [Test]
        public void OldEnumValueTest()
        {
            // TODO unit test for the property 'OldEnumValue'
        }
        /// <summary>
        /// Test the property 'NewEnumValue'
        /// </summary>
        [Test]
        public void NewEnumValueTest()
        {
            // TODO unit test for the property 'NewEnumValue'
        }
        /// <summary>
        /// Test the property 'OldMultiEnumValues'
        /// </summary>
        [Test]
        public void OldMultiEnumValuesTest()
        {
            // TODO unit test for the property 'OldMultiEnumValues'
        }
        /// <summary>
        /// Test the property 'NewMultiEnumValues'
        /// </summary>
        [Test]
        public void NewMultiEnumValuesTest()
        {
            // TODO unit test for the property 'NewMultiEnumValues'
        }
        /// <summary>
        /// Test the property 'NewApprovalStatus'
        /// </summary>
        [Test]
        public void NewApprovalStatusTest()
        {
            // TODO unit test for the property 'NewApprovalStatus'
        }
        /// <summary>
        /// Test the property 'OldApprovalStatus'
        /// </summary>
        [Test]
        public void OldApprovalStatusTest()
        {
            // TODO unit test for the property 'OldApprovalStatus'
        }
        /// <summary>
        /// Test the property 'DuplicateOf'
        /// </summary>
        [Test]
        public void DuplicateOfTest()
        {
            // TODO unit test for the property 'DuplicateOf'
        }
        /// <summary>
        /// Test the property 'DuplicatedFrom'
        /// </summary>
        [Test]
        public void DuplicatedFromTest()
        {
            // TODO unit test for the property 'DuplicatedFrom'
        }
        /// <summary>
        /// Test the property 'Dependency'
        /// </summary>
        [Test]
        public void DependencyTest()
        {
            // TODO unit test for the property 'Dependency'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Test]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

    }

}
