/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing TaskBaseAllOfExternal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskBaseAllOfExternalTests
    {
        // TODO uncomment below to declare an instance variable for TaskBaseAllOfExternal
        //private TaskBaseAllOfExternal instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskBaseAllOfExternal
            //instance = new TaskBaseAllOfExternal();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskBaseAllOfExternal
        /// </summary>
        [Test]
        public void TaskBaseAllOfExternalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TaskBaseAllOfExternal
            //Assert.IsInstanceOf(typeof(TaskBaseAllOfExternal), instance);
        }


        /// <summary>
        /// Test the property 'Gid'
        /// </summary>
        [Test]
        public void GidTest()
        {
            // TODO unit test for the property 'Gid'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
