/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing WebhookResponseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookResponseAllOfTests
    {
        // TODO uncomment below to declare an instance variable for WebhookResponseAllOf
        //private WebhookResponseAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebhookResponseAllOf
            //instance = new WebhookResponseAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookResponseAllOf
        /// </summary>
        [Test]
        public void WebhookResponseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WebhookResponseAllOf
            //Assert.IsInstanceOf(typeof(WebhookResponseAllOf), instance);
        }


        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'LastFailureAt'
        /// </summary>
        [Test]
        public void LastFailureAtTest()
        {
            // TODO unit test for the property 'LastFailureAt'
        }
        /// <summary>
        /// Test the property 'LastFailureContent'
        /// </summary>
        [Test]
        public void LastFailureContentTest()
        {
            // TODO unit test for the property 'LastFailureContent'
        }
        /// <summary>
        /// Test the property 'LastSuccessAt'
        /// </summary>
        [Test]
        public void LastSuccessAtTest()
        {
            // TODO unit test for the property 'LastSuccessAt'
        }
        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Test]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

    }

}
