/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using asana.Api;
using asana.Model;
using asana.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace asana.Test
{
    /// <summary>
    ///  Class for testing WebhookRequestFiltersInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookRequestFiltersInnerTests
    {
        // TODO uncomment below to declare an instance variable for WebhookRequestFiltersInner
        //private WebhookRequestFiltersInner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebhookRequestFiltersInner
            //instance = new WebhookRequestFiltersInner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookRequestFiltersInner
        /// </summary>
        [Test]
        public void WebhookRequestFiltersInnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WebhookRequestFiltersInner
            //Assert.IsInstanceOf(typeof(WebhookRequestFiltersInner), instance);
        }


        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Test]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }
        /// <summary>
        /// Test the property 'ResourceSubtype'
        /// </summary>
        [Test]
        public void ResourceSubtypeTest()
        {
            // TODO unit test for the property 'ResourceSubtype'
        }
        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Test]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }

    }

}
